version: 2

sources:
  - name: clickhouse
    schema: default
    tables:
      - name: stg_dim_payment
      - name: stg_fact_orders
      - name: stg_fact_returns
      - name: stg_orders
      - name: stg_payments
