name: 'dbt_clickhouse_dw'
version: '1.0.0'
config-version: 2

# dbt가 이 프로젝트에 연결하기 위해 사용할 profile 정의
profile: 'clickhouse_dw'

# dbt 프로젝트 디렉토리 경로 구조 설정
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# 모델 구체화(Materialization) 기본 설정
models:
  dbt_clickhouse_dw:
    +quote_columns: false
    +persist_docs:
      relation: true
      columns: true
    "01_bronze":
      +materialized: view
      +schema: bronze
    "02_silver":
      +materialized: table
      +schema: silver
    "03_gold":
      +materialized: table
      +schema: gold
